# Generated by Django 3.1.5 on 2021-02-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inituser',
            name='name',
        ),
    ]
