# Generated by Django 3.1.5 on 2021-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210213_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inituser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
