# Generated by Django 3.1.5 on 2021-01-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210125_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_submit',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework_uploads/'),
        ),
    ]
