# Generated by Django 3.1.5 on 2021-01-25 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_homework_submit_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 20, 14, 9, 300854), null=True),
        ),
        migrations.AddField(
            model_name='homework_submit',
            name='contents',
            field=models.TextField(null=True),
        ),
    ]
