# Generated by Django 3.1.5 on 2021-03-04 15:19

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210304_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profileimg/'),
        ),
    ]
