# Generated by Django 3.1.5 on 2021-01-25 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210125_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
