# Generated by Django 3.1.5 on 2021-01-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210125_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework_submit',
            name='homework_id',
            field=models.ForeignKey(db_column='homework_id', on_delete=django.db.models.deletion.CASCADE, to='mysite.homework'),
        ),
    ]
