# Generated by Django 3.1.5 on 2021-03-18 20:02

from django.db import migrations
import imagekit.models.fields
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20210304_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=mysite.models.profile_upload_to),
        ),
    ]
