# Generated by Django 3.1.5 on 2021-01-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20210125_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework_submit',
            name='user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
