# Generated by Django 3.1.5 on 2021-01-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20210125_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
